
FROM almalinux:9
# CMD [ "ping", "google.com" ]
# ENTRYPOINT [ "ping", "facebook.com"]


    # We can mention command in ENTRYPOINT, default options/inputs can be supplied through CMD. User can always override default options.

CMD [ "google.com" ]
ENTRYPOINT [ "ping"] 